@api = http://localhost:3000/tasks

GET {{api}}

###########
GET {{api}}/1

###########
GET {{api}}/count

#################
POST {{api}}
Content-Type: application/json

{
    "title": "five task",
    "description": "some description task 5"
}

################
DELETE {{api}}/5

########################
PUT {{api}}/1
Content-Type: application/json

{
    "title": "I have to dinner"   
}